import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const MostraNuova = localFont({
  src: [
    {
      path: '../public/fonts/MostraNuova-Light.woff',
      weight: '300',
      style: 'normal',
    },
    {
      path: '../public/fonts/MostraNuova-Regular.woff',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../public/fonts/MostraNuova-Bold.woff',
      weight: '700',
      style: 'normal',
    },
  ],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className= {`${MostraNuova.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
